### ISSUE TITLE
Complete Componentizing Form Elements

### ISSUE THREAD

**Issue by BransonGitomeh** [salsaUniversity/ember-university#5]
Finish the tiny Jquery stuff remaining, and help with the feilds and form segments needed in the new student forms

we getting closer :smile:

**Comment by gideon-maina** [comment]
Received the assignment today actually what jQuery do yu need there because I think what fisrt needs to be done is to get a clean finished UI then later on get on with the UX. 

Tell me your suggestion

**Comment by BransonGitomeh** [comment]
i meant this components


https://github.com/salsaUniversity/ember-university-client/blob/master/app/Modules/adminhome/new-student-form/template.hbs

i did those forms halfway....just clean it up an all components look :small_orange_diamond:  :smiling_imp:
